log:
  development: true
  console: true
  disableCaller: false
  disableStackTrace: false
  level: debug
  callerSkip: 1

jaeger:
  host: jaeger:14268
  serviceName: socrates
  logSpans: false

chatter:
  systemFilePath: /app/config/src

server:
  host: localhost
  port: 50505
